CLOUD_STORE_CONFIG_SERVER_PORT: 8903
CLOUD_STORE_CONFIG_ROUTE_SERVICE_URL: http://localhost:8904
CLOUD_STORE_CONFIG_BUCKET_SSL_CONNECT: false
CLOUD_STORE_CONFIG_MONGO_DB_CONNECTION_URL: mongodb://root:password@localhost:27017/cloud-store?authSource=admin
spring:
  application:
    name: cloud-store
  data:
    mongodb:
      uri: ${CLOUD_STORE_CONFIG_MONGO_DB_CONNECTION_URL}
server:
  port: ${CLOUD_STORE_CONFIG_SERVER_PORT}

    
      

