GATEWAY_CONFIG_BUCKETS_PROTOCOL_SECURE: false
GATEWAY_CONFIG_BUCKETS_SERVER_URL: http://localhost:8902
GATEWAY_CONFIG_ROUTE_SERVICE_URL: http://localhost:8904
spring:
  application:
    name: bucket-gateway
server:
  port: 8900
