BUCKET_SERVER_CONFIG_KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
BUCKET_SERVER_CONFIG_BUCKET_UPDATE_TOPIC: "bucket-updates"
spring:
  webflux:
    base-path: "/system-manager"
  application:
    name: bucket-server
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/buckets?authSource=admin
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: ${BUCKET_SERVER_CONFIG_KAFKA_BOOTSTRAP_SERVERS}
server:
  port: 8902