ROUTE_SERVICE_CONFIG_HEARTBEAT_BOOTSTRAP_SERVERS: "localhost:9092"
ROUTE_SERVICE_CONFIG_BUCKET_UPDATE_BOOTSTRAP_SERVERS: "localhost:9092"
ROUTE_SERVICE_CONFIG_BUCKET_HEARTBEAT_TOPIC: "buckets"
ROUTE_SERVICE_CONFIG_BUCKET_INFORMATION_UPDATE_TOPIC: "buckets-update"
spring:
  application:
    name: route-service
server:
  port: 8904
