spring:
  application:
    name: bucket-gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://127.0.0.1:8090/api/v1/files
          predicates:
            - Path=/server
server:
  port: 9090
