spring:
  application:
    name: file-service
  data:
    mongodb:
      username: root
      password: password
      host: 127.0.0.1
      port: 27017
      database: file-handler
      authentication-database: admin
server:
  port: 9506