BUCKET_CONFIG_MACHINE_IP_AUTO_DISCOVERY: true
BUCKET_CONFIG_STORAGE_PATH: "/home/akash/bukets/root_bucket"
BUCKET_CONFIG_GRPC_SERVICE_PORT: 9090
BUCKET_CONFIG_ID: "some-long-bucket-id"
server:
  port: 9991
spring:
  application:
    name: bucket
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
