CLOUD_STORE_CONFIG_SERVER_PORT: 8903
CLOUD_STORE_CONFIG_ROUTE_SERVICE_URL: http://localhost:8904
spring:
  application:
    name: cloud-store
  data:
    mongodb:
      uri: ${FILE_STORE.MONGO_URL}
server:
  port: ${CLOUD_STORE_CONFIG_SERVER_PORT}

