BUCKET_HOST_NAME_AUTO_DISCOVERY: true
BUCKET_UNIQUE_ID: 1
spring:
  application:
    name: bucket
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8090