FILE_STORE:
  SERVER_PORT: ${SERVER_PORT:8550}
  MONGO_URL: ${MONGO_URL:mongodb://root:password@localhost:27017/file-store?authSource=admin}
  GATEWAY_URL: ${GATEWAY_URL:http://localhost:9090}
spring:
  application:
    name: file-store
  data:
    mongodb:
      uri: ${FILE_STORE.MONGO_URL}
server:
  port: ${FILE_STORE.SERVER_PORT}

